### ISSUE TITLE
Scheduler breaks when multiple ships are in schedule

### ISSUE THREAD

**Issue by ezod** [ezod/aistweet#4]
The tweet scheduler breaks when multiple ships are in the schedule simultaneously. This seems to be a bug in [phluentmed/event-scheduler](https://github.com/phluentmed/event-scheduler), which can be reproduced by scheduling (and maintaining references to) two separate future events, and then canceling one of them.

**Comment by dil-mchaina** [comment]
@ezod I'm one of the maintainers of event-scheduler. I'll look into this issue

**Comment by dil-mchaina** [comment]
Would you be able to open an issue on our repository?

**Comment by ezod** [comment]
I sat down to do that, and actually can't seem to reproduce it now, at least not in the way that I thought I had a minimal example for. If I do reproduce it, I will open an issue at your end. Thanks.

**Comment by dil-mchaina** [comment]
We just fixed a bug in the cancel function that was probably related to your [issue](https://github.com/phluentmed/event-scheduler/pull/12). Update your event-scheduler version to >=0.1.2

**Comment by ezod** [comment]
@dil-mchaina Thanks, it appears to be fixed now! Closing.
